FROM python:3.10-slim

WORKDIR /app

# Обновляем pip
RUN pip install --upgrade pip

# Зависимости → кэш слоёв
COPY bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Код проекта
COPY bot/ .

# Бот обычно не слушает HTTP-порты (polling), но на всякий
EXPOSE 8080

CMD ["python", "bot.py"]
