FROM python:3.10-slim

WORKDIR /app

# Сразу обновили pip — и хватит
RUN pip install --upgrade pip

# Сначала зависимости, потом код (ради кэша)
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

EXPOSE 8080

CMD ["gunicorn", "--worker-class", "eventlet", "-w", "1", "--bind", "0.0.0.0:8080", "app:app"]
